---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: springboot
          image: sarthakwaghpatil/medicure:1.0
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
